[project]
site_url = "https://heig-vd-msci-course.github.io/heig-vd-msci-course/"
site_name = "Algorithmique et programmation (MSCI - ERACOM)"
# site_description = "Le dépôt du cours d'introduction à la programmation pour la maturité."
# site_author = "Fleurimont C. & Guidoux V."

# copyright = "Creative Commons Attribution-ShareAlike 4.0 International"

# repo_url = "https://github.com/heig-vd-msci-course/heig-vd-msci-course"
# repo_name = "heig-vd-msci-course/heig-vd-msci-course"
# edit_uri = "edit/main/docs/"

nav = [
  { "Accueil" = "index.md" },
  { "Équipe enseignante" = "equipe.md" },
  { "Programme" = [
    { "Lundi - Introduction" = "programme/jour1.md" },
    { "Mardi - Web" = "programme/jour2.md" },
    { "Mercredi - micro:bit" = "programme/jour3.md" },
    { "Jeudi - Travail libre" = "programme/jour4.md" },
    { "Vendredi - Projet" = "programme/jour5.md" },
  ]},
  { "Ressources" = [
    { "Guide du jeu des allumettes" = "supports/guide-jeu-allumettes.md" },
    { "Concepts algorithmiques" = "supports/cheatsheet-concepts-algo.md" },
    { "Charte de comportement" = "supports/template-charte-comportement.md" },
    { "Activité : Donner des instructions" = "supports/activities/activite-donner-instructions.md" },
    { "Template MakeCode Arcade" = "code-templates/makecode/jeu-allumettes-arcade.md" },
  ]},
]

# extra_css = ["stylesheets/extra.css"]
# extra_javascript = ["javascripts/extra.js"]

[project.theme]
# variant = "classic"
# custom_dir = "overrides"
# favicon = "images/favicon.png"
language = "fr"
features = [
  "announce.dismiss",
  # "content.action.edit",
  # "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  # "navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  # "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  # "navigation.tabs",
  # "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  # "toc.follow",
  # "toc.integrate",
]

# logo = "assets/logo.png"

# [project.theme.icon]
# logo = "lucide/smile"

# [project.theme.font]
# text = "Inter"
# code = "Jetbrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# [[project.extra.social]]
# icon = "fontawesome/brands/github"
# link = "https://github.com/user/repo"

# [[project.extra.social]]
# icon = "fontawesome/brands/mastodon"
# link = "https://fosstodon.org/@user"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc = {
  permalink = true
}
pymdownx.arithmatex = {
  generic = true
}
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji = {
  emoji_generator = "zensical.extensions.emoji.to_svg",
  emoji_index = "zensical.extensions.emoji.twemoji",
}
pymdownx.highlight = {
  anchor_linenums = true,
  line_spans = "__span",
  pygments_lang_class = true,
}
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets = {
#   base_path = "includes",
# }
pymdownx.superfences = {
  custom_fences = [
    {
      name = "mermaid",
      class = "mermaid",
      format = "pymdownx.superfences.fence_code_format",
    },
  ],
}
pymdownx.tabbed = {
  alternate_style = true,
  combine_header_slug = true
}
pymdownx.tasklist = {
  custom_checkbox = true
}
pymdownx.tilde = {}
